//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPIPServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font-family:Lucida Console;font-size:10px;color:Green;")]
        public string StyleGreen
        {
            get
            {
                return ((string)(this["StyleGreen"]));
            }
            set
            {
                this["StyleGreen"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font-family:Lucida Console;font-size:10px;color:Red;")]
        public string StyleRed
        {
            get
            {
                return ((string)(this["StyleRed"]));
            }
            set
            {
                this["StyleRed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font-family:Lucida Console;font-size:10px;color:Blue;")]
        public string StyleBlue
        {
            get
            {
                return ((string)(this["StyleBlue"]));
            }
            set
            {
                this["StyleBlue"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font-family:Lucida Console;font-size:10px;color:Black;")]
        public string StyleBlack
        {
            get
            {
                return ((string)(this["StyleBlack"]));
            }
            set
            {
                this["StyleBlack"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font-family:Lucida Console;font-size:10px;color:Purple;")]
        public string StylePurple
        {
            get
            {
                return ((string)(this["StylePurple"]));
            }
            set
            {
                this["StylePurple"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font-family:Lucida Console;font-size:10px;color:Orange;")]
        public string StyleOrange
        {
            get
            {
                return ((string)(this["StyleOrange"]));
            }
            set
            {
                this["StyleOrange"] = value;
            }
        }
    }

}
